name: Python Application

on:
  workflow_dispatch:
  push:

jobs:
  python-build-n-publish:
    name: Build and publish Python distribution
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

    - name: Run tests
      run: python ./run_tests.py test
