name: Pytest Framework Template with CICD pipeline
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - uses: actions/checkout@v4
        if: success() || failure()
      - run: |
          python run_tests.py
          chmod 777  /home/runner/work/Pytest_Framework_Template/Pytest_Framework_Template/Reports/

      - name: Set output
        if: success() || failure()
        id: results
        run: echo "artifactPath=Reports/" >> $GITHUB_OUTPUT

      - uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: test-report
          path: ${{ steps.results.outputs.artifactPath }}
