name: Python Application

on:
  workflow_dispatch:
  push:

jobs:
  python-build-n-publish:
    name: Build and publish Python distribution
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -U pytest

      - name: Print working directory and list files
        run: |
          pwd
          ls -R

      - name: Run tests
        run: pytest ./Testcases/Test_testsuite.py --html=Reports/Reports.html
  

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: Reports/Reports.html
